MCU_LDSCRIPT = STM32F103x8

CUSTOM_MATRIX = lite

PLOVER_HID_ENABLE = yes
# STENO_ENABLE = yes
# STENO_PROTOCOL = geminipr

COMBO_ENABLE = yes

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = pwm

SRC += matrix.c multisteno.c